# Generated by Django 5.2.16 on 2026-07-18 14:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('intern', 'Sales intern'), ('manager', 'Manager'), ('system_admin', 'System admin')], db_index=True, default='intern', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('website', models.URLField(max_length=500)),
                ('short_description', models.TextField(max_length=1000)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_linkedin_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('next_action', models.CharField(blank=True, max_length=250)),
                ('next_action_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('not_yet_responded', 'Not yet responded'), ('not_interested', 'Not interested'), ('meeting_to_be_scheduled', 'Meeting to be scheduled'), ('meeting_scheduled', 'Meeting scheduled'), ('meeting_done', 'Meeting done')], db_index=True, default='not_yet_responded', max_length=40)),
                ('meeting_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prospects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Sales intern responsible for this prospect.', on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_action_date', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('medium', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('outreach_date', models.DateField()),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_outreaches', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='outreach.prospect')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['owner', 'status'], name='outreach_pr_owner_i_9e1b09_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['owner', 'next_action_date'], name='outreach_pr_owner_i_a1a93a_idx'),
        ),
        migrations.AddConstraint(
            model_name='outreach',
            constraint=models.UniqueConstraint(fields=('prospect', 'sequence_number'), name='unique_prospect_outreach_number'),
        ),
        migrations.AddConstraint(
            model_name='outreach',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gte', 1), ('sequence_number__lte', 5)), name='outreach_number_between_1_and_5'),
        ),
    ]
