# Generated by Django 5.2.16 on 2026-07-20 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_playbook_state(apps, schema_editor):
    Prospect = apps.get_model('outreach', 'Prospect')
    Outreach = apps.get_model('outreach', 'Outreach')
    status_stages = {
        'not_interested': 'closed',
        'meeting_to_be_scheduled': 'interested',
        'meeting_scheduled': 'founder_meeting_booked',
        'meeting_done': 'meeting_completed',
    }
    for status, stage in status_stages.items():
        Prospect.objects.filter(status=status).update(stage=stage)
    Outreach.objects.filter(sequence_number__gt=1).update(activity_type='follow_up')


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='activity_type',
            field=models.CharField(choices=[('connection_request', 'LinkedIn connection request'), ('connection_accepted', 'LinkedIn connection accepted'), ('initial_outreach', 'Initial outreach'), ('follow_up', 'Follow-up'), ('material_sent', 'One-page overview or deck sent'), ('close_loop', 'Close-the-loop message'), ('inbound_response', 'Prospect response'), ('phone_call', 'Phone call'), ('voicemail', 'Voicemail'), ('founder_escalation', 'Escalated to founder'), ('meeting_handoff', 'Founder meeting handoff')], default='initial_outreach', max_length=40),
        ),
        migrations.AddField(
            model_name='prospect',
            name='client_segment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prospect',
            name='consulting_focus',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prospect',
            name='eligibility_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='founder_account',
            field=models.CharField(blank=True, choices=[('kandarp_soni', 'Kandarp Soni (Chicago)'), ('sunit_kala', 'Sunit Kala (Florida)')], max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='founder_escalation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='founder_escalation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='interest_signal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='linkedin_connection_status',
            field=models.CharField(blank=True, choices=[('not_sent', 'Connection request not sent'), ('request_sent', 'Connection request sent'), ('accepted', 'Connection accepted'), ('declined', 'Declined or not now')], max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prospect',
            name='material_shared',
            field=models.CharField(blank=True, choices=[('', 'Nothing shared'), ('one_page', 'One-page overview'), ('short_deck', 'Short introductory deck'), ('one_page_and_deck', 'One-page overview and short deck')], max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_participants',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_timezone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='prospect',
            name='personalization_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='prospect',
            name='questions_for_founders',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('interested', 'Interested'), ('founder_meeting_booked', 'Founder meeting booked'), ('meeting_completed', 'Meeting completed'), ('closed', 'Closed')], db_index=True, default='eligible', max_length=40),
        ),
        migrations.AddField(
            model_name='prospect',
            name='workstream',
            field=models.CharField(choices=[('intern', 'Sales intern'), ('inside_sales', 'Inside sales'), ('linkedin_outreach', 'LinkedIn outreach')], db_index=True, default='intern', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('intern', 'Sales intern'), ('inside_sales', 'Inside sales'), ('linkedin_outreach', 'LinkedIn outreach'), ('manager', 'Manager'), ('system_admin', 'System admin')], db_index=True, default='intern', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(help_text='Outreach operator responsible for this prospect.', on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_playbook_state, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['workstream', 'stage'], name='outreach_pr_workstr_b994bf_idx'),
        ),
    ]
