# Generated by Django 5.2.16 on 2026-07-20 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_outreach_activity_type_prospect_client_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='import_key',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prospect',
            name='import_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Outreach operator responsible for this prospect.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('research', 'Research required'), ('eligible', 'Eligible'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('interested', 'Interested'), ('founder_meeting_booked', 'Founder meeting booked'), ('meeting_completed', 'Meeting completed'), ('closed', 'Closed')], db_index=True, default='eligible', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key', ''), _negated=True), fields=('workstream', 'import_key'), name='unique_imported_firm_per_workstream'),
        ),
    ]
