# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0005_api_access_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="is_not_eligible",
            field=models.BooleanField(default=False, verbose_name="Is not eligible"),
        ),
        migrations.AddField(
            model_name="prospect",
            name="prospect_sent",
            field=models.BooleanField(default=False, verbose_name="Prospect sent"),
        ),
        migrations.CreateModel(
            name="ProspectUpdateAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("api", "API")],
                        default="api",
                        max_length=20,
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("changed_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prospect_update_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_audits",
                        to="outreach.prospect",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
