# Generated by Django 5.2.16 on 2026-08-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0006_prospect_flags_and_update_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                (
                    "target_workstream",
                    models.CharField(
                        choices=[
                            ("intern", "Sales intern"),
                            ("inside_sales", "Inside sales"),
                            ("linkedin_outreach", "LinkedIn outreach"),
                        ],
                        max_length=30,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.JSONField(default=list)),
                ("created_rows", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Imported"),
                            ("partially_rolled_back", "Partially rolled back"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("rolled_back_count", models.PositiveIntegerField(default=0)),
                ("rollback_skipped_rows", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_prospect_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolled_back_prospect_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prospect_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="prospect",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prospects",
                to="outreach.prospectimportbatch",
            ),
        ),
    ]
