# Generated by Django 5.2.16 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0007_prospect_import_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachUpdateAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("api", "API")],
                        default="api",
                        max_length=20,
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("changed_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outreach_update_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outreach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_audits",
                        to="outreach.outreach",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
